version: '3.8'

services:
  nce-flow:
    build: .
    container_name: nce-flow
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      # 如果需要在运行时更新内容，可以挂载卷
      # - ./NCE1:/usr/share/nginx/html/NCE1
      # - ./NCE2:/usr/share/nginx/html/NCE2
      # - ./NCE3:/usr/share/nginx/html/NCE3
      # - ./NCE4:/usr/share/nginx/html/NCE4
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nce-network

networks:
  nce-network:
    driver: bridge
